project:
  type: book
  output-dir: _book
  post-render:
    - add-extra-files.R

execute:
  freeze: auto

book:
  title: "A Handfull of Pixels"
  subtitle: "big science using small data"
  author: "Koen Hufkens"
  date: "2023/03/28"
  page-navigation: true
  chapters:
    - index.qmd
    - part: intro.qmd
      chapters:
      - basic_R.qmd
    - gathering_data.qmd
    - geospatial_R.qmd
    - part: "Worked Examples"
      chapters:
      - phenology_detection.qmd
      - land_cover_classification.qmd
      - phenology_modelling.qmd
    - references.qmd
  appendices:
    - appendix_setup.qmd
    - appendix_licensing.qmd
    - appendix_config.qmd
  favicon: "figures/favicon.ico"
  twitter-card: true
  search: true
  repo-url: https://github.com/khufkens/handfull_of_pixels/
  sharing: [twitter, facebook]
  navbar:
    title: " "
    logo: ""
    background: "#0b2735"
    search: true
    right:
      - text: "Home"
        file: index.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: [cosmo, theme-light.scss]
      dark: [cosmo, theme-dark.scss]
