project:
  type: book
  output-dir: _book
  post-render:
    - add-extra-files.R

book:
  title: "A Handfull of Pixels"
  subtitle: "big science using small data"
  author: "Koen Hufkens"
  date: "2023/03/28"
  page-navigation: true
  chapters:
    - index.qmd
    - intro.qmd
    - basicr.qmd
    - getting_data.qmd
    - geospatialr.qmd
    - appendix.qmd
    - references.qmd
  favicon: "figures/favicon.ico"
  twitter-card: true
  search: true
  repo-url: https://github.com/khufkens/handfull_of_pixels/
  sharing: [twitter, facebook]
  navbar:
    title: " "
    logo: ""
    background: "#0b2735"
    search: true
    right:
      - text: "Home"
        file: intro.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: [cosmo, theme-light.scss]
      dark: [cosmo, theme-dark.scss]
